name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout Code
      uses: actions/checkout@v1
      with:
        submodules: true      
        
    - name: Install SDK
      run: |
        mkdir sdk
        mkdir toolchain
        cd sdk
        wget https://www.nordicsemi.com/-/media/Software-and-other-downloads/SDKs/nRF5/Binaries/nRF5SDK153059ac345.zip
        unzip nRF5SDK153059ac345.zip
        cd ../toolchain
        wget https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2 -O gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2
        tar xjf gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2
        cd ..
        patch -p0 < nrfx_uart.patch
        pushd sdk/nRF5_SDK_15.2.0_9412b96/external/micro-ecc
        export GNU_INSTALL_ROOT="$PWD/../../../../toolchain/gcc-arm-none-eabi-7-2018-q2-update/bin/"
        git clone https://github.com/kmackay/micro-ecc.git
        make -C nrf52hf_armgcc/armgcc
        make -C nrf52nf_armgcc/armgcc
        popd

    - name: Build
      run: |
        cd 02_Bootloader
        clean
        make
        make hex
